### ISSUE TITLE
Default gaia hub read issues

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/gaia#101]
Several app developers are reporting read issues with the default Gaia hub hosted by Blockstack PBC. 

Richard Adjei [Today at 4:53 AM]
in #engineering
I would say the main issue is the servers are occasionally failing to recover files from storage even though the files exist.  And the files that load are also taking a while.  It could be due to our app requesting too many files at the same time and Gaia storage not being designed to handle that many accesses.  But I can say for sure so I just wanted to inform blockstack.

7 replies
avthar [3 hours ago]
As a caveat, this may also be a problem with the programming patterns we use to load stuff from GAIA. We’re following the examples laid out in the Blockstack tutorials though so I’m not sure if there’s too much more improvement on that front (edited)

JustinHunter [2 hours ago]
I've seen this behavior when trying to load more than one file on page load (ex: in componentDidMount method in React). I think it's good to bring it up. My solution has been a sub-optimal solution performance wise, but if I need that second (or third or whatever) file, I set a refresh call to keep fetching the file just to make sure I eventually get it.

avthar [2 hours ago]
thanks for sharing your experience — I think it’s the same issue —  we’re trying to load like 5 files on the same page lol

**Comment by larrysalibra** [comment]
I tried to replicated this by modifying the blockstack-todos app to write ~10 ~ 1 megabyte files and immediately read the same files back. My browser got really slow but didn't see any errors from gaia.blockstack.org.

**Comment by brandonparee** [comment]
Is the "slowness" caused by the download itself, or the decryption of files?

**Comment by larrysalibra** [comment]
> Is the "slowness" caused by the download itself, or the decryption of files?

Tried it again with encryption/decryption disabled. It's the encryption that was slowing it down for me! Thanks for pointing that out @brandonparee
