### ISSUE TITLE
Add Google Cloud Storage Driver

### ISSUE THREAD

**Issue by stern0** [blockstack/gaia#103]
There are drivers for S3 and Azure Blob, I am working implementing Google Cloud Storage.

**Comment by jackzampolin** [comment]
Awesome @stern0! Should be very similar to the S3 one. I'm guessing you are using the node sdk for Google Cloud? https://github.com/GoogleCloudPlatform/google-cloud-node

**Comment by stern0** [comment]
@jackzampolin Sure I am using the google cloud storage client https://github.com/googleapis/nodejs-storage

**Comment by stern0** [comment]
PR: https://github.com/blockstack/gaia/pull/105

**Comment by kantai** [comment]
Thanks for the PR @stern0! That's merged into `develop`, and should be included in master in the next release.

**Comment by stern0** [comment]
👍
