### ISSUE TITLE
Flow type checks consistency

### ISSUE THREAD

**Issue by stern0** [blockstack/gaia#104]
Within the gaia codebase I have seen areas like [server.js](https://github.com/blockstack/gaia/blob/master/hub/src/server/server.js) where there are `flow` type checks , I think would be best if flow type checks were used throughout the codebase or not used at all as it doesn't look consistent. At first glance I wasn't sure if it was Typescript or JS.

**Comment by stern0** [comment]
@kantai do you think gaia would benefit from Typescript? It seems to have a better type system than flow.

**Comment by kantai** [comment]
Thanks for raising this issue

I suspect that Typescript can be nicer to use than flow, however, Blockstack uses flow for most of its Javascript codebase (rather than TS), so for consistency, it'd be best to use flow here as well. I'm going to merge flow annotations into develop soon.

**Comment by stern0** [comment]
👍
