### ISSUE TITLE
Driver specs

### ISSUE THREAD

**Issue by stern0** [blockstack/gaia#106]
This isn't an issue but a question.
@kantai mentioned in issue https://github.com/blockstack/gaia/issues/79 about pinning down a spec for gaia hub drivers. Obviously the current drivers are simple and it's easy to implement new ones. Is there a spec yet or Is there one in writing?

**Comment by kantai** [comment]
The closes thing we have to a spec right now is the description here:

https://github.com/blockstack/gaia/blob/master/README.md#driver-model

The biggest feature request that would have an impact on this driver model in the near term is https://forum.blockstack.org/t/feature-request-gaia-ls-functionality/4769
