### ISSUE TITLE
help needed for setting gaia hub to aws

### ISSUE THREAD

**Issue by liphan** [blockstack/gaia#112]
I'm trying to set up gaia hub with my aws s3 bucket (am using windows computer), by following the steps listed here https://github.com/blockstack/gaia/tree/master/hub, but after I add aws credential in config file and do "npm run start", localhost:3000 shows "cannot get"

**Comment by robert-bo-davis** [comment]
I believe that is expected behavior.

You should be able to see information about the running hub at http://localhost:3000/hub_info/.

**Comment by liphan** [comment]
http://localhost:3000/hub_info/ shows the following:
{"challenge_text":"[\"gaiahub\",\"2018\",\"hub.blockstack.org\",\"blockstack_storage_please_sign\"]","read_url_prefix":"https://gaia.blockstack.org/"}

**Comment by kantai** [comment]
Closing this out as this appears to have been running correctly --

We also describe in the hub/README how to test your configuration with test writes:

https://github.com/blockstack/gaia/blob/master/hub/README.md#run-the-tests
