### ISSUE TITLE
Add check to authentication which requires the URL to be communicated

### ISSUE THREAD

**Issue by kantai** [blockstack/gaia#127]
We can add a requirement to the authentication which ensures that the authentication token was generated by a client intending to communicate with this gaia hub -- basically, just add a claim like:

```
hubUrl: "https://hub.blockstack.org"
```

And then the Gaia hub asserts that the hubURL in the authentication token matches the one that the hub expects of itself.

**Comment by jcnelson** [comment]
Shipped!
