### ISSUE TITLE
Public list-files

### ISSUE THREAD

**Issue by jcnelson** [blockstack/gaia#131]
Make it possible, through a configuration option in the Gaia hub, to list files publicly via a GET endpoint.

**Comment by robert-bo-davis** [comment]
It seems like setting this option on a gaia hub level could delegate too much authority to the administrator of a hub.

If I'm using Jill's gaia hub, I don't want Jill to be able to enable public list for my endpoints. I, as a user or developer, want to have control over that permission. I may also want some endpoints on the same hub to have public list enabled while others do not.

Would it make sense for this permission to exist as part of the per app gaia hub records in the zone file as discussed in #102? Or perhaps a configuration file within the gaia hub endpoint could be used to enable/disable public list?

**Comment by kantai** [comment]
I agree with @robert-bo-davis, but would also add that I think that having some gaia hubs supporting this and other not supporting it presents a strange programming model to would-be developers, and would prefer that this not be a feature.

**Comment by jcnelson** [comment]
I see what you mean.  In light of #96, it might make sense to make the `POST /list-files/${address}` endpoint permissioned, somehow.  The authentication token could permit listing the contents of the `${address}` bucket if it was signed by one of a set of keys listed in the `whitelist` array in the config file.

**Comment by kantai** [comment]
> I see what you mean. In light of #96, it might make sense to make the POST /list-files/${address} endpoint permissioned, somehow. The authentication token could permit listing the contents of the ${address} bucket if it was signed by one of a set of keys listed in the whitelist array in the config file.

Perhaps, though, I like the simplicity of the current authentication model, basically a JSON token needs to be signed by the key associated with the bucket to perform any "authenticated" actions on the bucket. And, as currently conceived, the whitelist keys should always be able to generate the child keys. However, if we were going to extend the authentication model, it'd be nice to permission not just list-files, but also, specific write files (so I can generate a token that says, this token holder can only write file `/..../xyz.foo`), but I'd want to wait on extending the authentication model any further until we have pretty compelling use cases for that.

**Comment by jcnelson** [comment]
I think this is will be addressed with scoped authentication tokens (#142).  Listing files is private, but the ability to list (but not write) files can be delegated by the hub owner.  Going to go ahead and close this issue in favor of #142.
