### ISSUE TITLE
Gaia gateway

### ISSUE THREAD

**Issue by jcnelson** [blockstack/gaia#134]
As a piece of ancillary tooling, add a gateway process that handles the following endpoints:

* `GET /${blockstack_id}/${address}/${filename}`:  Fetches the given `${filename}` from the given `${blockstack_id}`.  For example, `GET /ryan.id/1FrZTGQ8DM9TMPfGXtXMUvt2NNebLiSzad/status.json` should resolve to `[{"id":0,"text":"Hello, Blockstack!","created_at":1515786983492}]`.

* `GET /${blockstack_id}`:  Fetches the list of application URLs and Gaia bucket IDs (i.e. app addresses) for a particular user.  This is taken straight from the `apps` object in the Blockstack ID's profile.

The purpose of this gateway is to make it easy to share files stored in Gaia with the rest of the Web.

**Comment by yknl** [comment]
Does this endpoint fetch data from other Gaia hubs as well or is it limited to data stored on the hub itself?

**Comment by jcnelson** [comment]
It fetches from any Gaia hub.  It's online now: https://gaia-gateway.com
