### ISSUE TITLE
Write tutorial for setting up your own Gaia hub

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/gaia#137]
* create `docs` directory to contain user facing documentation
* move the muti-player-storage.md tutorial to docs/multi-player-storage.md (?)
* tutorials we will need
  - local storage for end-users
  - developer storage through cloud hosting (Azure, etc)

**Comment by moxiegirl** [comment]
I think, perhaps, browser documentation should actually contain "understand and choose storage options" is something all users might do. As long as we have the browser around.  

Most users would probably use the default hub. Then, there are users that want to migrate to the default, that migrate doc should live here.

Migrating TUTORIAL would require probably one document that explains:
* Understand what other non-default options are available.
* Configure a personal storage service (e.g. Azure, AWS) to use GAI
* Use the CLI to migrate your data there from the default hub
* Set up the browser to use the hub for apps

We will likely also need tutorials for developers who want to build and offer their own GAIA storage.  Presumably, that would be service they offer either for their own apps or in general.

**Comment by markmhx** [comment]
@moxiegirl That all sounds right to me, and I believe those four bullet points in particular map to my understanding of what we need to document for the CLI's release. Any thoughts on where this should live?

@jcnelson is there anything you'd add, modify or subtract here for release?

**Comment by jcnelson** [comment]
Looks good to me for now :+1:.  One thing I'd emphasize in the tutorial is the ability to view your Gaia hub's data in the underlying storage system (e.g. in S3 directly), so we hammer home the point that you control where your data gets stored and have direct access to it outside of the application.

**Comment by markmhx** [comment]
@jcnelson great, and I agree we want to emphasize the power of seeing where your data gets stored. That said, if someone loads it up on S3 directly, they see everything encrypted and can't actually open it, correct?

@moxiegirl do you have all the guidance you'd need to start working on this and given your other priorities, know when we might be able to review a draft? @jcnelson will you need to release any more changes to the CLI before you recommend that she test with it?

**Comment by jcnelson** [comment]
> @jcnelson great, and I agree we want to emphasize the power of seeing where your data gets stored. That said, if someone loads it up on S3 directly, they see everything encrypted and can't actually open it, correct?

They should be unable to read their encrypted data without tooling, but they should know that it is there and should be able to (in a pinch) use the CLI to decrypt it.

They should be able to directly download and view their unencrypted data.

> @jcnelson will you need to release any more changes to the CLI before you recommend that she test with it?

I'm going to expand the built-in help documentation some more, and fix a couple bugs in the authenticator I discovered over the weekend.  Then it'll be ready for @moxiegirl.

**Comment by markmhx** [comment]
@jcnelson sounds good, thanks! Please let us know here when it's ready for @moxiegirl.

It'd be nice to see some info in this documentation on how to decrypt the data in your hub using the CLI as well. I don't think it's as high priority as the other items listed, though, so perhaps we can consider those instructions desirable but optional for this release.

**Comment by moxiegirl** [comment]
@markmhx I'll start with the source that @jcnelson is going to provide.  @jcnelson please make sure to add a `docs` directory here on `gaia` for customer facing docs.

@markmhx If I get an early link to the source, I'll have a better idea on the ETA on this particular piece.   I had understood from the conversation in the Gaia meeting this morning that @GInxh and @wileyj felt that an end user storage option was not that close.  

@jcnelson can you clarify, is this tutorial for the savvy developer that knows S3, Azure etc, or is this for the end user that uses a tool we provide which hides that aspect?  It doesn't matter much to me either way, I just want to make sure we are all talking about the same thing.

**Comment by jcnelson** [comment]
> @jcnelson can you clarify, is this tutorial for the savvy developer that knows S3, Azure etc, or is this for the end user that uses a tool we provide which hides that aspect? It doesn't matter much to me either way, I just want to make sure we are all talking about the same thing.

This is for a savvy developer.

**Comment by moxiegirl** [comment]
CLI was covered and closed by a separate issue: https://github.com/blockstack/docs.blockstack/issues/58
Tutorial now covered here: https://github.com/blockstack/docs.blockstack/issues/80
