### ISSUE TITLE
Create dedicated website for Gaia

### ISSUE THREAD

**Issue by markmhx** [blockstack/gaia#141]
This entails creating a dedicated website for Gaia so developers can learn about it and get started with development apart from Blockstack.

The specification can be found here: https://paper.dropbox.com/doc/Gaia-website-specification--ALOb6_2C93xM3YpR3U17uUz4Ag-9beIbRJOZuhGbLIp2EEcD

The WIP design can be previewed here: https://s.codepen.io/markmhendrickson/debug/e5f242d0eae52642a84dce3abc80be47

I'm taking a minimalist, content-centric approach to the design to start before turning much attention to the site's aesthetics (e.g. creating a color palette or vector-based graphics such as icons or diagrams for the various sections).

However, I'm thinking we may want to go with a green and blue earthy aesthetic, for natural (ha) reasons. I think an organic feel with subtle animations that makes the site feel alive and lush could be tied well to the conceptual idea that Gaia fosters an ecosystem of life aka apps that are interconnected via energy aka data.

**Comment by wileyj** [comment]
Looks decent, I like the minimalist design. 
However, the one thing that sticks out to me is the "...52 apps use gaia".
As more apps are added we'd have to keep updating this. Maybe a generic count like "Many apps use Gaia currently", followed by the button "Browse All Apps"

**Comment by markmhx** [comment]
I'm closing this out until we decide to prioritize work on a website for Gaia again.
