### ISSUE TITLE
Explainer for how to update a name and/or subdomain's zone file to point to a new Gaia hub

### ISSUE THREAD

**Issue by markmhx** [blockstack/gaia#143]
Originally added as a card by @jcnelson for https://github.com/orgs/blockstack/projects/30

**Comment by markmhx** [comment]
@moxiegirl does this appear like the right kind of task to throw your way or should I bat it back to @jcnelson?

**Comment by moxiegirl** [comment]
@markmhx This is something I would work on with @jcnelson. Essentially, he can write a rough of the steps and any guidance -- tips or tricks he recommends.  Then, I'll test the steps and write a tutorial around this.

Sound ok?

**Comment by markmhx** [comment]
@moxiegirl That sounds perfect, thanks!

**Comment by moxiegirl** [comment]
closing in favor of issue here: https://github.com/blockstack/docs.blockstack/issues/79
