### ISSUE TITLE
Disk driver: need to preserve content-type on read

### ISSUE THREAD

**Issue by jcnelson** [blockstack/gaia#146]
All drivers preserve the MIME type of the data upload, so the storage provider can serve data with the same MIME type in the `Content-Type` header.  The disk driver does not do this.  Moreover, there isn't a straightfoward way to do reads for data stored via the disk driver -- the read server would need to be cognizant of the disk driver's method for storing MIME type metadata in order to reply the correct content.

**Comment by markmhx** [comment]
@larrysalibra is this related to the request you shared with me the other day?

**Comment by larrysalibra** [comment]
It's related to this: 
https://github.com/blockstack/blockstack.js/pull/552 and https://github.com/blockstack/blockstack.js/issues/551

**Comment by jcnelson** [comment]
PR submitted:  https://github.com/blockstack/gaia/pull/155

**Comment by jcnelson** [comment]
Merged to master!
