### ISSUE TITLE
Programmatic endpoint for setting the initial whitelist

### ISSUE THREAD

**Issue by jcnelson** [blockstack/gaia#152]
This is an open question to think about -- if a user is contacting their Gaia hub for the first time, can they programmatically set the initial address whitelist?  The use-case is the user registering a Blockstack ID and pointing it to their freshly-deployed private Gaia hub.  They don't have an address for it yet, and we don't want to have the user navigate away from the onboarding flow to go manually add the address.

One option is to have the user set a one-time-use password when they instantiate their Gaia hub, and then enter it into the onboarding flow along with the Gaia write endpoint.  In the background, the authenticator POSTs to the Gaia hub to set the initial whitelist once the name registration transactions and zone file gets generated and queued up.

**Comment by kantai** [comment]
I'm not sure how this would work actually -- the whitelist is currently configured by a config option. That's written to disk (or possibly set via env var).

**Comment by hstove** [comment]
I brought this up before you joined, but it would essentially be another need for Gaia to be able to maintain state (via a DB or something). The other need being would be for tracking revoked tokens. Writing to disk would not be ideal

**Comment by hstove** [comment]
At some point, I don't see a future where Gaia doesn't maintain state. If I'm a service provider providing a hosted hub, with payments, I need a programatic way to maintain my whitelist. Thus this API could be generalized to simply "Programmatic endpoint for updating the whitelist".

**Comment by jcnelson** [comment]
Actually, I was thinking that if we implemented this feature, it would be realized as a separate administrative service.  There would be no need to modify the Gaia daemon proper.  A separate, co-located service would be responsible for maintaining the config file and feeding it into the Gaia hub.

We don't have to do this for Q4 (or possibly ever); was just trying to get us thinking about how we might do this.

**Comment by hstove** [comment]
>  There would be no need to modify the Gaia daemon proper. A separate, co-located service would be responsible for maintaining the config file and feeding it into the Gaia hub.

Yes, for sure, by default you should be able to run Gaia without any statefulness, no matter how it's implemented.

**Comment by jcnelson** [comment]
This could be addressed by the admin side-car PR if the user knew the API key beforehand (which I'm assuming they would).

**Comment by jcnelson** [comment]
This is addressed by the admin side-car.  I consider this issue resolved.
