### ISSUE TITLE
Gaia hub should enforce optional max file size

### ISSUE THREAD

**Issue by jcnelson** [blockstack/gaia#154]
Right now, this is done as part of a forward proxy like nginx.  It would be nice if this setting (and all settings for that matter) are set via config.json.

**Comment by kantai** [comment]
The forward proxy is much more robust for closing connections that are too large than node's HTTP library.

**Comment by jcnelson** [comment]
Looks like the default deployment strategy for Gaia hubs is shaping up to running it behind an nginx proxy anyway.  Going to go ahead and close this with EWONTFIX (use a proxy to enforce this).
