### ISSUE TITLE
dflkdksn

### ISSUE THREAD

**Issue by GInxh** [blockstack/gaia#166]
ddgdg

**Comment by markmhx** [comment]
@GInxh I'm closing this issue out since I assume you were just testing something when you created it?

**Comment by ghost** [comment]
I will be deleting my github and per github policy all code & comments in repositories I do not own will remain (production will not be impacted) and replaced with github general ghostuser account https://github.com/ghost

Please edit your comments to remove the "@myusername" here as other peoples mentions of my username, which I want deleted. 

When the "@myusername" is appropriately removed, I will also remove this comment.

All comments that do not mention my username explicitly are to remain UNEDITED by me per the open source archive standards, but all comments mentioning my username are not necessary in the comments for open source development so deleting them will not be an issue.

Thank you!
