### ISSUE TITLE
Create simple README around Docker Compose 

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/gaia#180]
@GInxh will add a bit of description around this.

**Comment by GInxh** [comment]
Documentation for testing on local host using env vars to support mounting on localhost is reported for macosx. The configuration should also work for Linux (do try at home).

These need to be exported on host or defined in the .env file. Do not push .env file changes for localhost testing.

**Comment by GInxh** [comment]
https://github.com/blockstack/gaia/blob/feature/docker-compose/docker/README.md
