### ISSUE TITLE
Docker build of /hub fails in `develop`

### ISSUE THREAD

**Issue by kantai** [blockstack/gaia#186]
Upgrading our blockstack.js dependency pulls in secp25k-tiny -- which depends on Python to `npm install` -- but our Dockerfile is an alpine nodejs image, so it doesn't have Python installed.

@wileyj thinks we should address this in all our (potentially affected) Dockerfiles by creating our own image which derives from alpine-node and adds Python. That way, we won't have to repeat these changes for other repos that depend on blockstack.js.

**Comment by wileyj** [comment]
I'm handling this in our builds currently by sed'ing the base image in Dockerfile to `blockstack/node:latest`. 
Builds using this method are succeeding, but we should determine if this is the route we want to take. I'm not currently tagging these builds as `latest` or `master`. 

The `blockstack/node:latest` image is just the `node:8-alpine` base image with a few additional deps required for secp25k-tiny.
