### ISSUE TITLE
Change Amazon account name from Halfmoon

### ISSUE THREAD

**Issue by markmhx** [blockstack/gaia#200]
cc @moxiegirl to send @markmhx a link to how images are listed

**Comment by moxiegirl** [comment]
So, imagine our AMI appearing in a search here:

![image](https://user-images.githubusercontent.com/1347209/52234750-40822100-2877-11e9-89fb-add5aff09a2c.png)

Also the community

https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:

**Comment by markmhx** [comment]
**Title**: Blockstack Gaia Hub

**Description** (modified from [the Gaia README](https://github.com/blockstack/gaia#overview)): 


> Gaia works by hosting data in one or more existing storage systems of the user's choice. These storage systems are typically cloud storage systems. We currently have driver support for S3 and Azure Blob Storage, but the driver model allows for other backend support as well. The point is, the user gets to choose where their data lives, and Gaia enables applications to access it via a uniform API.
>
> Blockstack applications use the Gaia storage system to store data on behalf of a user. When the user logs in to an application, the authentication process gives the application the URL of a Gaia hub, which performs writes on behalf of that user. The Gaia hub authenticates writes to a location by requiring a valid authentication token, generated by a private key authorized to write at that location.
>
> This AMI makes it easy to install and run a Gaia hub on EC2 with S3 as a storage system.

**More info URL**: *whatever URL that's most relevant to the API within the new Gaia documentation that @moxiegirl is preparing*

**Image URL**: https://docs.blockstack.org/assets/posts/touch-icon.png

**Comment by markmhx** [comment]
@wileyj to follow up with Amazon since he hasn't heard back yet

**Comment by wileyj** [comment]
Access has been gained. AMI is currently in the review process and will go to marketplace afterwards.
