### ISSUE TITLE
Write forum post about new Gaia hub documentation

### ISSUE THREAD

**Issue by markmhx** [blockstack/gaia#201]

**Comment by moxiegirl** [comment]
@markmhx Proposed text.  Please feel free to adjust in a comment to this issuel

> Today we published documentation for the Gaia feature in docs.blockstack.org.  This documentation is intended for a developer audience.  It includes the following topics:

> * An introduction to the storage architecture
> * An overview of how authentication works with Gaia
> * Explanation of how developers can configure a custom Hub choice for Users
> * Hub configuration reference
> * How to run a Gaia hub on DigitalOcean
> * How to run a Gaia hub on AWS EC2
> 
> This documentation is searchable just as the rest of our documentation. We will continue to add and update this content. 
> 
> If you use the documentation and encounter problems or would like to make a suggestion, [please file an issue](https://github.com/blockstack/docs.blockstack/issues).

**Comment by markmhx** [comment]
@moxiegirl Looks good! Here's a revision with some added language about our motivations and recommendations. Would love your thoughts:

> Today we published new documentation for Blockstack's storage system, Gaia, in docs.blockstack.org. This documentation is intended for a developer audience and includes the following topics:
>
> * Introduction to the storage architecture
> * Overview of how authentication works with Gaia
> * Explanation of how developers can empower users to configure recommended or custom Gaia hubs
> * Gaia hub configuration reference
> * How to run a Gaia hub on DigitalOcean
> * How to run a Gaia hub on Amazon AWS (EC2)
> 
> We hope this documentation helps Blockstack developers deepen their understanding of Gaia and implement decentralized storage to maximum effect in their applications.
>
> Developers are encouraged to set up Gaia hubs and recommend them to users during onboarding depending on those users' needs. For example, an enterprise customer may need their data stored in a storage provider to which they have direct access, and a developer could host a Gaia hub that helps connect the user's Blockstack ID to that storage provider.
>
> Developers are also encouraged to help educate technically proficient users about Gaia hubs by pointing them to this documentation and enabling hub configuration during onboarding. Users of such applications could then configure Blockstack IDs to use Gaia hubs they personally deploy and manage.
>
> This documentation is searchable just like the rest of our documentation. We will continue to add and update this content. 
> 
> If you use the documentation and encounter problems or would like to make a suggestion, [please file an issue](https://github.com/blockstack/docs.blockstack/issues).

**Comment by moxiegirl** [comment]
@markmhx Looks fine to me. Of course, I'll add a link to the docs at the end of the post.

**Comment by moxiegirl** [comment]
This was done. https://forum.blockstack.org/t/gaia-amis-for-ec2-and-gaia-documentation/7512
