### ISSUE TITLE
Collections: Support event-log write operation where existing file is renamed and history is kept

### ISSUE THREAD

**Issue by yknl** [blockstack/gaia#220]
To be completed

**Comment by markmhx** [comment]
@zone117x will work with @yknl to update this issue with the latest thinking

**Comment by markmhx** [comment]
@zone117x @yknl Is one of you actually working on this at the moment or should we move it to the backlog for now? It's been "in progress" for a month now.

**Comment by yknl** [comment]
This is currently in progress
