### ISSUE TITLE
Azure Driven Gaia Hub returns 500 Errors on Concurrent Writes

### ISSUE THREAD

**Issue by kantai** [blockstack/gaia#228]
Concurrent POSTs on the same file will return 500 server failures -- the error kicked back from Azure is "InvalidBlockList".

You can duplicate this behavior by running a local instance, configured against an Azure backend, and running some parallel POSTs on the same file (I figured this out running apache bench).

**Comment by markmhx** [comment]
We'll also implement unit tests for concurrent writes on all the drivers

**Comment by kantai** [comment]
We should probably return something like a 400 error with a JSON message saying "Concurrent writes disallowed"
