### ISSUE TITLE
Collections: Note in readme that requests from same bucket should be handled by single Gaia hub

### ISSUE THREAD

**Issue by yknl** [blockstack/gaia#235]
For a couple existing items (revocation) and future items (renames), correct functioning of the Gaia hub requires that a given _bucket_'s requests are handled by a single Gaia hub instance. This is to handle synchronized paths in the Gaia code (i.e., check-and-sets).

This is really only relevant for Gaia deployments that run in a clustered way.

**Comment by zone117x** [comment]
Repo now contains notes around concurrency control and clustering.
