### ISSUE TITLE
Default Gaia Hub rate limiting causes CORS errors

### ISSUE THREAD

**Issue by kantai** [blockstack/gaia#239]
Currently, the default Gaia hub rate limits via Cloudflare -- so end-users will receive the Cloudflare "429" error message. Unfortunately, that 429 page doesn't set permissive CORS headers, nor does it return a JSON-y error code for blockstack.js to parse.

We will probably need to rework our rate limiting setup (likely enforcing on our end) to address this issue.

**Comment by markmhx** [comment]
@kantai How many times have we heard this bug reported to date? I seem to remember once in the community Slack.

Also, is Cloudflare rate limiting by IP address or something else?

**Comment by zone117x** [comment]
Seems like this issue should be opened in a devops repo. Closing for now.
