### ISSUE TITLE
Application Level Data Store

### ISSUE THREAD

**Issue by hdriqi** [blockstack/gaia#244]
From the documentation, I know that gaia can easily store & retrieve data for authenticated user. 

How about storing/retrieving data for app level? For example list of all users that already registered on the app which available for everyone.

**Comment by hstove** [comment]
This would require quite a few changes to Gaia to support this. Gaia doesn't have any knowledge of which "buckets" belong to which user/app, although a lot of that data can be found by indexing on-chain data.

Another option is to use [Radiks](https://github.com/blockstack-radiks/radiks), which aggregates every user's Gaia data for a particular app.

**Comment by hdriqi** [comment]
@hstove i see, thanks for the information
