### ISSUE TITLE
Instructions to run own gaia hub & upgrade

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/gaia#251]
This issue is an ask for instructions for the following:

1. setting up a gaia hub on an arbitrary linux server - not something that only works on AWS (the AWS image doesn't get updated)
2. instructions on how to configure a gaia hub for the exclusive use of one person or a small group of people (admin instructions say "To set the whitelist, you must set the entire whitelist." but don't explain how a user generates whitelists for her Blockstack IDs)
3. instructions for on-going maintenance and upgrade. if someone is going to start storing their data on a gaia hub, they need to know how to upgrade and maintain it.

**Comment by moxiegirl** [comment]
Issue moved to [blockstack/docs.blockstack #316](https://github.com/blockstack/docs.blockstack/issues/316) via [**ZenHub**](https://www.zenhub.com/)
