### ISSUE TITLE
Support SSL config in node.js

### ISSUE THREAD

**Issue by zone117x** [blockstack/gaia#252]
Following up discussion around nginx adding potentially unnecessary pain to gaia hub setup --

> @zone117x : is it still the case its generally recommended to not directly expose a node.js http server at port 80/443? this was a general idea I recall from like 5 years ago but not sure its true anymore.
seems to me the only benefit for custom hub runners that nginx provides is ssl/letsencrypt support, which we could relatively easily add support for in js, I think

> @kantai: It definitely used to be the case that people recommended against exposing app servers directly to oncoming traffic
Hence nginx
But I’m not sure if it’s still all that necessary
It does make it so that every app server doesn’t need to include the same boiler plate for SSL, Header processing (and enforcement of correct content length)

**Comment by moxiegirl** [comment]
@zone117x apologies for the reopen. I was testing the x-workspace pipeline issues
