### ISSUE TITLE
Add `Access-Control-Max-Age` header in POST requests

### ISSUE THREAD

**Issue by tautvilas** [blockstack/gaia#254]
Currently because each POST request to store file is CORS request browser sends an OPTIONS request before making an actual POST. This is impacting performance of all apps because 2 requests are sent instead of 1. This could be easily mitigated by adding Access-Control-Max-Age header to requests. If the header was added only the first request to the resource would do additional OPTIONS request.

More info about OPTIONS: https://stackoverflow.com/questions/29954037/why-is-an-options-request-sent-and-can-i-disable-it

I can do a PR if you prefer

**Comment by zone117x** [comment]
Implemented in https://github.com/blockstack/gaia/pull/255 and in the dev branch.

Will be available on the public gaia hub once deployed to master and prod.
