### ISSUE TITLE
Adding Website Data (non personal) to Gaia

### ISSUE THREAD

**Issue by theallegrarr** [blockstack/gaia#271]
I understand working with Gaia after reading through the info in the blockstack docs, but i dont understand how i can use it for general data and shared date. Examples of these are;

Discussion between two app users
Forum threads that contain inputs from many different users
General website data that will be accessible to all users on the website

In summary, i want to know how some info can be generalized or made accessible to a group of users based on their connection to the specific data

**Comment by moxiegirl** [comment]
@theallegrarr  As you asked this on the forum as a support question and it was answered, I'm going to close this. For reference, the forum post is here:

https://forum.blockstack.org/t/how-do-i-create-shared-data-on-gaia-storage/9156/2
