### ISSUE TITLE
How can I get my notes data back? The data was stored on the Gaia. Seems disappeared.

### ISSUE THREAD

**Issue by Miahelloworld** [blockstack/gaia#342]
**Describe the bug**
I am a user of noteriot dapp. Several days ago, I found my previous notes cannot show up on noteriot webpage, however it can show the latest days’s notes. Only around 12 notes on my noteriot dapp now, more that 30 notes cannot show up.

Here is the website link.

https://note.riot.ai/notes

**Expected behavior**
1. How can I download my previous notes data which was stored on Gaia? So that I can find my important data back.
2. Is there a tool that I can download the notes data, and easily to read.

**Screenshots**
![47B1B1F4-798F-44FA-A6B0-4F14E7E51FF8](https://user-images.githubusercontent.com/72310174/121987974-18524780-cdcc-11eb-8ca3-8162aecdac28.jpeg)
![959F8AE3-23E7-4426-9230-8282B815EB9E](https://user-images.githubusercontent.com/72310174/121987985-1ee0bf00-cdcc-11eb-8410-59214422a4c7.jpeg)
![9FBCA76A-E142-459D-966A-BA31463AD0BE](https://user-images.githubusercontent.com/72310174/121987990-20aa8280-cdcc-11eb-8936-5ee549f96e3d.jpeg)
![D056CFB9-F734-4423-9473-3448FA7434BB](https://user-images.githubusercontent.com/72310174/121987994-22744600-cdcc-11eb-8204-4b322f79b84b.jpeg)
![A6792D4D-B1AA-40B5-8B06-508E6C896AAE](https://user-images.githubusercontent.com/72310174/121988004-26a06380-cdcc-11eb-9366-97639c1b18a0.jpeg)

**Something else I want to know**
1. If the user didn’t delete his data on the Gaia, can the dapp program itself has the chance and possibility delete the data?
2. I also asked the founder of noteriot on discord, told me to try the commands, but he also don’t know how to find my previous data back.

**Console log**

I typed`blockstack.getFile("riotnotes.json")’

Then, I typed `blockstack.getFile("backups/2021-06-05-riotnotes.json")`

Then, Tried with 06-04,06-03,06-02  same error alert.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [i tried the brave,safari,and Firefox browser]
 - Version [mojave]

@jcnelson @dantrevino @zone117x @diwakergupta

**Comment by Miahelloworld** [comment]
@CharlieC3

**Comment by CharlieC3** [comment]
Hey @Miahelloworld, I looked into this for you. I've confirmed your notes are safe in Gaia storage:
![Screen Shot 2021-06-17 at 10 16 46 AM](https://user-images.githubusercontent.com/2747302/122414465-2aabbd00-cf55-11eb-8994-8efc47a7414a.png)


However, it seems the Riotnotes app may be querying for them with the wrong file name. For example, you can find your notes from June 5th, 2021 here:
https://gaia.blockstack.org/hub/18afXT1iPZM7SyCHokCtVHXpicu1jRGXX8/backups/2021-6-5-riotnotes.json

The Riotnotes app appears to be looking for the filename `2021-06-05-riotnotes.json`, where the month and day digits are formatted differently.

There hasn't been any changes made to Gaia that would cause files to be renamed in any way, so I'm wondering if there's been an update to Riotnotes recently that would affect how it persists and retrieves files from Gaia. If you're able to forward this info to the Riotnotes founder, they may be able to help more.

**Comment by Miahelloworld** [comment]
> Hey @Miahelloworld, I looked into this for you. I've confirmed your notes are safe in Gaia storage:
> ![Screen Shot 2021-06-17 at 10 16 46 AM](https://user-images.githubusercontent.com/2747302/122414465-2aabbd00-cf55-11eb-8994-8efc47a7414a.png)
> 
> However, it seems the Riotnotes app may be querying for them with the wrong file name. For example, you can find your notes from June 5th, 2021 here:
> https://gaia.blockstack.org/hub/18afXT1iPZM7SyCHokCtVHXpicu1jRGXX8/backups/2021-6-5-riotnotes.json
> 
> The Riotnotes app appears to be looking for the filename `2021-06-05-riotnotes.json`, where the month and day digits are formatted differently.
> 
> There hasn't been any changes made to Gaia that would cause files to be renamed in any way, so I'm wondering if there's been an update to Riotnotes recently that would affect how it persists and retrieves files from Gaia. If you're able to forward this info to the Riotnotes founder, they may be able to help more.

Thanks, I will transfer this info to the noteriot founder.

**Comment by Miahelloworld** [comment]
@CharlieC3  I found this tool on github and stacks forum, https://github.com/MichaelFedora/mercurius.  
but it requires the 12 words of recovery key. But my recovery key are 24 words. and I can use that 24 words of recovery key login the noteriot, but i cannot use that aia Hub File Explorer.  Do you official team have a tool for users that I can easily access my gaia data ?? It is really important for our users!!!!!

**Comment by CharlieC3** [comment]
@Miahelloworld Was the Noteriot founder able to help you retrieve your data?

**Comment by Miahelloworld** [comment]
> @Miahelloworld Was the Noteriot founder able to help you retrieve your data?

i have talking with him, but need to set the dev environment to retrieve my data. Too complex, I need a simple way.

**Comment by CharlieC3** [comment]
> I found this tool on github and stacks forum, https://github.com/MichaelFedora/mercurius

I'm guessing this tool is quite old, from the Stacks 1.0 days. That may be why it only accepts 12-word phrases. I would also be very careful inputting your 24-word phrase into custom tools around the webs you aren't familiar with. It could be a honeypot to steal keys.

> i have talking with him, but need to set the dev environment to retrieve my data

I'm not aware of any other method to retrieve and decrypt the data, so this may be your best bet for now.

Looping in @reedrosenbluth and @kantai in case they have any other ideas.

**Comment by Miahelloworld** [comment]
@reedrosenbluth @kantai  Please, do you have the ways to retrieve my notes data from the Gaia?

**Comment by CharlieC3** [comment]
@Miahelloworld would it be helpful if I could send you a zip of your encoded data? I don't know how you'd decode it, but it would at least let you access all of it easily.

**Comment by Miahelloworld** [comment]
how can you have my zip of encoded data without having my recovery key? @CharlieC3

**Comment by Miahelloworld** [comment]
please send my zip of encoded data to blockstackbrowser@protonmail.com

**Comment by wileyj** [comment]
@Miahelloworld try this dapp to access your stored data: https://xordrive.io/

**Comment by dantrevino** [comment]
Part of the issue here is that I never got the restore functionality added to noteriot.  I'm working on this now.

The data is encrypted with stacks 1.0 app private key, which uses the hostname ... the way to get the data unencrypted outside of the application is impersonate note.riot.ai, ... the easiest way to do this:
1. install node version 8.9.0
2. clone the git repo @ gitlab.com/riot.ai/noteriot
3. `npm install`
4. update your hosts file to make 127.0.0.1 resolve to note.riot.ai
5. `npm run dev`
6. open a dev console
7. at the console type `blockstack.getFile("backups/2021-6-5-riotnotes.json").then(data => console.log(JSON.parse(data)))`

**Comment by wileyj** [comment]
thanks @dantrevino 
@Miahelloworld the node install is available here if you need it: https://nodejs.org/download/release/v8.9.0/

Once that's installed, you should be able to run the commands referenced in a terminal (windows may call it something different if you're on windows). 

For the hosts file, this should be helpful: https://linuxize.com/post/how-to-edit-your-hosts-file/

**Comment by Miahelloworld** [comment]
blockstack.getFile("backups/2021-6-5-riotnotes.json").then(data => console.log(JSON.parse(data)))

this command works.

**Comment by CharlieC3** [comment]
> blockstack.getFile("backups/2021-6-5-riotnotes.json").then(data => console.log(JSON.parse(data)))
> 
> this command works.

Awesome! I would suggest using this method to get your notes back if it works.
