### ISSUE TITLE
Shared storage driver

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/gaia#69]
This is discussion continued from https://github.com/blockstack/blockstack-core/issues/584

Design Goals:
- Should be able to wrap a number a number of backends
- Should be able to handle an arbitrary number of users
- Should check those users addresses or profile verifications to allow writes

@muneeb-ali @jcnelson @kantai @larrysalibra

**Comment by kantai** [comment]
I think the engineering team on this is going to be @jackzampolin and I!

Okay -- from our design meeting -- the plan is construct something like a "Gaia Hub" which authenticates writes using end user's bitcoin addresses. Reads will be performed out of band.

User addresses must be associated with social verifications for spam protection, and eventually a name should be registered for the address, or the allocated storage will be reaped.

**Comment by kantai** [comment]
There's basically two pieces of this:

1. the server which is authenticating writes, initializing the storage backend (in the initial case, s3 bucket), and forwarding the writes. hopefully we can write pass-through to s3 
1. the storage driver in blockstack-core -- this should be really straight-forward

Also, unless someone has a strong argument otherwise, the server is going to be written for nodeJS. The goal is for the server to be basically stateless (apart from the spam protection -- which should at least be trivially shardable)

**Comment by jackzampolin** [comment]
Could we use nginx for their rate limiting and keep that code out of node?

**Comment by kantai** [comment]
That's a great idea.

**Comment by jackzampolin** [comment]
I'll go ahead and stub out a `/hub` directory with a node server that can make an s3 call to get this started.

**Comment by kantai** [comment]
Okay -- initial thought for the format of write requests.

`PUT /{address}/{path}`

The `PUT` data will just be the bytes to store.

The request will need to have some specific headers:

`X-BLOCKSTACK-SOCIAL-PROOF`
`AUTHENTICATION: bearer XYZ`

The Authentication bearer token (`XYZ` above), should be a signature over an endpoint specific challenge, say: 

`gaiahub-{date}-{hub_server_url}-{hub_server_challenge}`

The `{date}` ensures that these authentication tokens expire. The `{hub_server_url}` and the `{hub_server_challenge}` ensures that the signed token is only valid for this server.

The Content-Length header will also be important.

**Comment by kantai** [comment]
@jcnelson raised a good point that maybe we should put the social proofs into the Authentication header as well -- some software strips custom headers, and we'd prefer not to lose the social proof headers.

**Comment by jackzampolin** [comment]
This is done! Lets go ahead and close this issue.
