### ISSUE TITLE
Hub returns 503s when saving multiple files simultaneously

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/gaia#88]
Moving from: https://github.com/blockstack/blockstack.js/issues/337

If you try to save multiple files at the same time:

```javascript
Promise.all([
  blockstack.putFile('foo.json', '{}', true),
  blockstack.putFile('bar.json', '{}', true),
  blockstack.putFile('bim.json', '{}', true)
])
```

some or all of the requests error out with 503 Service Unavailable

tagging @kantai @nmuth

**Comment by nmuth** [comment]
To answer @kantai's question:

> I believe that this behavior is related to rate-limiting on the gaia service we provide.

> We have a pretty conservative rate limit there at the moment. Do you see this behavior consistently with just putting 2-3 files at a time?

Yep, it occurred almost every time when I put 3 files.

**Comment by larrysalibra** [comment]
@bodymindarts also ran into this problem.

I'm tagging it as a bug because the rate limiting behavior isn't clearly communicated to developers and or documented anywhere.

**Comment by kantai** [comment]
We adjusted the rate limit and aren't seeing this issue as frequently. This is documented here:

https://github.com/blockstack/gaia#notes-on-our-deployed-service

Long term, we'd prefer users run their own deployed hubs, which wouldn't need to impose any such rate limits.

Closing this issue, as it's deployment specific, and now documented.
