### ISSUE TITLE
Make Gaia Hub Deployable by Users

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/gaia#89]
Currently this is not possible.

**Comment by larrysalibra** [comment]
What needs to change for this to be deployable by users on their own azure, s3, etc accounts?

**Comment by jackzampolin** [comment]
Sound like this is going to require a couple of things:
- Data Migration Tooling
- Zonefile Updates
- Browser Configuration

**Comment by mingrui** [comment]
Does this mean I can't use my own dropbox with gaia?
So it is currently impossible to build a dapp that can store a very large (200gb) file?
Thank you!

**Comment by mingrui** [comment]
Thank you for the detailed answer.

I tried the one-click deploy on heroku and it went through.
But I'm a bit  confused about what happens after I have my own hub running on heroku.

How do I connect my gaia browser to my new hub? In the browser settings, I tried to change the `URL for Gaia Hub Connection` to point to `https://genstack.herokuapp.com/` (this is my hub address on heroku), but I don't think my apps  are saving to my hub.

Thanks!

**Comment by kantai** [comment]
Hey @mingrui -- apps don't correctly read the user's gaia hub URL in the current version of blockstack.js. Issue for that is here:

https://github.com/blockstack/blockstack.js/issues/390

Cleaning this up is something that is a short-term goal for the team, and we hope to release a patch for that soon. (We want to test it to make sure it doesn't break authentication in a surprising way).

**Comment by markmhx** [comment]
@jcnelson This issue seems to map broadly to the project https://github.com/orgs/blockstack/projects/30#card-12762962 now.

Can we close it out as such, and do we first need to break out any new issues for that project that capture work specified here?

**Comment by jcnelson** [comment]
I think the main points in this issue are now addressed in the project you linked.  You can close this.
