### ISSUE TITLE
Create documentation on Gaia Storage

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/gaia#90]

**Comment by kantai** [comment]
Documentation in https://github.com/blockstack/gaia

Tagging @yknl for reviews

**Comment by jcnelson** [comment]
Sent a PR with my review.

**Comment by yknl** [comment]
This looks good to me!

**Comment by larrysalibra** [comment]
Let's do review, changes & discussion via a pull request in the future!

Marking this as accepted.
