### ISSUE TITLE
Create an introduction to managing data in Gaia for the developer audience

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/gaia#91]
We already have great tutorials showing how to build simple apps with Gaia, but there's not a place where developers can just read about how Gaia works at a conceptual level. It would be good to have a post where we explain how you can manage app data with Gaia.

This could also be a series:
Post 1: Working with Data Collections
Post 2: Maintaining and Scaling Data
Post 3: Sharing Data with Others

**Comment by cwackerfuss** [comment]
Here's the working draft of an introduction plus Post 1 (Working with Data Collections)

https://paper.dropbox.com/doc/Managing-Data-with-Gaia-1jgJ9i2Yxz04JkxLEUWTL?_tk=share_copylink

**Comment by markmhx** [comment]
@moxiegirl Is this proposal and draft helpful to complete such an introduction that you're tracking with this issue? Or are you tracking such introductory material work elsewhere and we should close this issue in favor of there?

**Comment by moxiegirl** [comment]
@markmhx yes, this will form the basis.

**Comment by markmhx** [comment]
@moxiegirl Great, does it make sense to update this issue's title or specification to match the latest thinking on its deliverable?

I realize it was creating back in February by someone else, so just want to make sure it still clearly represents the objective you're working on.

**Comment by markmhx** [comment]
@moxiegirl I've assigned this to you since the latest comments here seem to suggest you were prioritizing work on this, though I'm not sure if that's still the case since the issue hasn't been updated since September.

I see the "Implement storage with Gaia" option in [the docs](https://docs.blockstack.org/) redirects to this repo. Is there a plan in motion to replace that redirect with a section that includes pages that address this issue's goals?

**Comment by moxiegirl** [comment]
@markmhx You are correct, I hadn't been prioritizing this work over the other. Now that the wallet and app.mining bits are out. I want to finish the cli work and then switch to this.

**Comment by markmhx** [comment]
@moxiegirl Sounds good. Given that this issue is so stale, could you create either a separate issue for this Gaia documentation addition *or* an epic with several issues (in case it's easier to track the create of several documentation pages for Gaia across distinct issues) then share the link here?

**Comment by moxiegirl** [comment]
@markmhx  Sure, I'll close this one when I create the others.  An Epic doesn't make sense tho --- do you have an epic you created for the initial Gaia work. I can add my issues there.

**Comment by markmhx** [comment]
There's an epic for work towards the release of Gaia hub URL choice during onboarding, but given that this documentation isn't a dependency, I'd suggest we keep it out of that scope. Perhaps it'd be best to just add the issue in the docs repo and label it with Gaia.

**Comment by moxiegirl** [comment]
@markmhx Some of the documentation will be a dependency. That is the documentation that Virginia is writing.

I had planned to add this to docs yes, I'll cross link any issues that require it and close this as I said.

**Comment by markmhx** [comment]
Cool, to be clear though. I view Hank’s onboarding work as far as adding Gaia hub URL choice as a separate project / epic than Virginia’s easy hub installlation image work.

I agree this new documentation will be a dependency for the latter project. I don’t think she’s created an epic for it yet, so I’ll do that today and link to it here.

**Comment by moxiegirl** [comment]
@markmhx you'll want to create a milestone for this not an epic.  An epic is for long-lived thematic projects that span sprints and repositories. This is a part of a milestone within a current sprint.

**Comment by markmhx** [comment]
Isn't this going to span two repositories though – this one and https://github.com/blockstack/docs.blockstack?

**Comment by moxiegirl** [comment]
Now tracked here: https://github.com/blockstack/docs.blockstack/issues/81
