### ISSUE TITLE
As a user concerned about the possibility of centralization in gaia, I should have a document which explains how users can truly own and operate their data through gaia

### ISSUE THREAD

**Issue by kantai** [blockstack/gaia#94]

**Comment by mingrui** [comment]
User can't operate their own gaia at this time right?

**Comment by jackzampolin** [comment]
@mingrui Not _quite_ yet, but we have completed most of the work to enable users to run their own hub. We need to enable it with a new release of the browser which will be shipped in the coming weeks.

**Comment by kantai** [comment]
This issue is about documenting the gaia protocol, and how users can deploy their own hubs and interact with them. That's already described in the README for this repo, and supported by gaia today, though clients still need to add support for this. Closing this issue out, as its about gaia documentation, which is done.
