### ISSUE TITLE
As a user, I should be able to one-click deploy a working gaia hub to Heroku

### ISSUE THREAD

**Issue by kantai** [blockstack/gaia#95]

**Comment by jackzampolin** [comment]
The plan is to use the [bucketeer](https://elements.heroku.com/addons/bucketeer) app to automatically generate AWS creds for the end user while the app is being provisioned. I will also provide in depth step by step instructions.

**Comment by yknl** [comment]
Just an idea, is there any value to enable the Gaia hub to read/write storage on the machine it's being hosted from? (A local storage driver basically) This could potentially simply the setup process.

**Comment by jackzampolin** [comment]
https://github.com/blockstack/gaia/issues/86

**Comment by jackzampolin** [comment]
I've got this implemented in https://github.com/blockstack/gaia/pull/97

**Comment by jackzampolin** [comment]
Looks like @kantai has merged that PR. I'm going to go ahead and close this issue!
